version: '3.8'

services:
  backend:
    build: ./Backend
    container_name: booking-backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:./prisma/dev.db
    volumes:
      - ./Backend/prisma:/app/prisma
    networks:
      - booking-network
    restart: unless-stopped

  bot-user:
    build: ./Bot_User
    container_name: booking-bot-user
    ports:
      - "3001:3001"
    environment:
      - USER_BOT_TOKEN=${USER_BOT_TOKEN}
      - WEBAPP_URL=${WEBAPP_URL}
    depends_on:
      - backend
    networks:
      - booking-network
    restart: unless-stopped

  bot-admin:
    build: ./Bot_Admin
    container_name: booking-bot-admin
    ports:
      - "3002:3002"
    environment:
      - ADMIN_BOT_TOKEN=${ADMIN_BOT_TOKEN}
    depends_on:
      - backend
    networks:
      - booking-network
    restart: unless-stopped

  frontend:
    build: ./Frontend/restaurant-booking-twa
    container_name: booking-frontend
    ports:
      - "80:80"
    networks:
      - booking-network
    restart: unless-stopped

networks:
  booking-network:
    driver: bridge